# Generated by Django 2.2.4 on 2019-08-09 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagem',
            new_name='image',
        ),
    ]
